### ISSUE TITLE
Getting Fatal: Failed to register the Ethereum service: Not implemented:

### ISSUE THREAD

**Issue by SwatGuard** [wemixarchive/go-wemix#105]
#### System information

Geth version: `geth version` 
Gwemix
Version: 0.10.8-stable
Git Commit: 53273fcb3729c477c62cd0215d4c90dcd3cb5d83
Git Commit Date: 20240604
Architecture: amd64
Go Version: go1.19.13
Operating System: linux

OS & Version: Windows/Linux/OSX
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
Commit hash : (if `develop`)

#### Expected behaviour
gwemix.sh should start

#### Actual behaviour

Getting 
Fatal: Failed to register the Ethereum service: Not implemented: Unsupported compression method for this build: Snappy

libsnappy-dev is already the newest version (1.1.8-1build3).
#### Steps to reproduce the behaviour
run gwemix.sh start

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by SwatGuard** [comment]
This also happens if I try to use a systemd service with parameters:
Example service:


`[Unit]
Description=Geth Execution Layer Client service
Wants=network-online.target
After=network-online.target
[Service]
Type=simple
User=wemix
Restart=on-failure
RestartSec=3
TimeoutSec=300
ExecStart=/home/wemix/wemix-node/gwemix \
--mainnet \
--http.api eth,web3,net \
--ws \
--http \
--ws.api eth,web3,net \
--http.vhosts='*' \
--ws.addr 0.0.0.0 \
--ws.port 8546 \
--http.addr 0.0.0.0 \
--http.port 8545 \
--ws.origins="*" \
--cache=96000 \
--rpc.gascap=0 \
--rpc.txfeecap=0 \
--datadir=/home/wemix/wemix-data \
--metrics \
--metrics.addr 0.0.0.0 \
--metrics.port 6070 \
--syncmode full \
--pprof 
[Install]
WantedBy=multi-user.target`

I'm using rocksdb data. I even tried downloading the latest snapshot and I get the same error:

`Fatal: Failed to register the Ethereum service: Not implemented: Unsupported compression method for this build: Snappy`

Are other flags required ?

**Comment by egonspace** [comment]
The previously uploaded file(`gwemix-master-53273fcb3729c477c62cd0215d4c90dcd3cb5d83-linux-amd64-rocksdb.tar.gz`) was an incorrectly built binary.

We uploaded the binaries that were built normally again, so please get them again on the next page.

https://github.com/wemixarchive/go-wemix/releases/tag/w0.10.8

**Comment by SwatGuard** [comment]
Seems to be OK now. Thanks for solving this.
