### ISSUE TITLE
gwemix(v0.10.8) does not work.

### ISSUE THREAD

**Issue by egonspace** [wemixarchive/go-wemix#106]
#### System information

Geth version: v0.10.8-stable
OS & Version: Linux
Commit hash : 53273fcb3729c477c62cd0215d4c90dcd3cb5d83

#### Actual behaviour
If we run `gwemix`, we meet the following error.

```
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./temp3/bin/gwemix)
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./temp3/bin/gwemix)
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./temp3/bin/gwemix)
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./temp3/bin/gwemix)
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./temp3/bin/gwemix)
./temp3/bin/gwemix: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./temp3/bin/gwemix)
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by egonspace** [comment]
It seems there is a problem in ci building artifact.

#105  related.

**Comment by jed-wemade** [comment]
I think this issue occurs due to binary using newest glibc.
Downgrading ubuntu version specified in ci file resolves the issue.

**Comment by SwatGuard** [comment]
Got the same errors yesterday on ubuntu 20. Upgrading to 22 solved the issue for the yesterday's version.
